### ISSUE TITLE
Github upload Portion Pt. 6 (nothing added to commit but untracked files present) 

### ISSUE THREAD

**Issue by Dallas-Alfonso** [basir/amazona#46]
Good Afternoon Basir,

Thank you for the tutorial.  When I move .gitignore from src to root, I get the terminal error: "nothing added to commit but untracked files present."

**Comment by Dallas-Alfonso** [comment]
The untracked files for me were:
.gitignore 
/frontend
/template

My solution was:

git add .gitignore
git add /frontend
git add /template

**Comment by alfredo0607** [comment]
hola buenas basir estoy realizando el proyecto y me da error 500 a la hora de subir la imagen del producto, ¿que puedo hacer?
