### ISSUE TITLE
Issue while trying to seed the application off fresh fork and install

### ISSUE THREAD

**Issue by JohnSasser** [basir/amazona#47]
Hello Basir, thank you for providing this as a reference and making this code available.  I went through some of the tutorials on YouTube and thought I would try to fork and start fresh from your repo.  I was having an issue with running the seed URL on localhost.
from: " 5. Seed Users and Products
Run this on chrome: http://localhost:5000/api/users
It returns admin email and password ";
```
{
"message": "ENOENT: no such file or directory, stat '/Users/johnsasser/Desktop/SandBox/amazona/frontend/build/index.html'"
}
```
is the return message from the req.  
I got 500 internal server err on the GET req. 
I received the same results from both seeding instructions.  Is there something simple I am missing?

**Comment by SebastienGras** [comment]
Hello,
I just wanted to know if you had success to resolve the issue?
And if yes, how please :) ?

**Comment by basir** [comment]
hello there
I had a bug fix for running locally.
clone it now and follow the instruction on readme to run it.

**Comment by SebastienGras** [comment]
thanks you basir :) i will test

**Comment by SebastienGras** [comment]
it works fine thanks you very much, just one thing, maybe you have to tell on readme that the password for users seed is 1234 ^^
it is not indicated i believe :) good day !
